WestwindSolution/WestwindWebApp/Pages/Products/Query.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

#region namepsaces for BLL and Entities
using WestWindSystem.BLL;
using WestWindSystem.Entities;
#endregion


namespace WestwindWebApp.Pages.Products
{
    public class QueryModel : PageModel
    {
        #region Setup constructor DI for BLL
        private readonly CategoryServices _categoryServices;
        private readonly ProductServices _productServices;

        public QueryModel(CategoryServices categoryServices, ProductServices productServices)
        {
            _categoryServices = categoryServices;
            _productServices = productServices;

            // Fetch from the system (CategoryServices) a list of Category
            CategoryList = _categoryServices.List();
            CategorySelectionList = new SelectList(_categoryServices.List(), "Id", "CategoryName", SelectedCategoryId); //populate dropdown selection menu

        }
        #endregion

        #region Properties to populate Category select element and track is selected value
        public List<Category> CategoryList { get; private set; }
        [BindProperty]
        public int? SelectedCategoryId { get; set; }

        public SelectList CategorySelectionList { get; private set; }
        #endregion

        [BindProperty]
        public string? QueryProductName { get; set; }

        [TempData]
        public string? FeedbackMessage { get; set; }

        public List<Product> QueryResultList { get; private set; }

        public void OnGet()
        {

        }

        public void OnPostSearchByCategory()
        {
            FeedbackMessage = "You click on Search By Category";
            QueryResultList = _productServices.FindProductsByCategoryId(SelectedCategoryId.Value);
            //return RedirectToPage(new { currentSelectedCategoryId = SelectedCategoryId });
        }

        public void OnPostSearchByProductName()
        {
            FeedbackMessage = "You click on Search By Product Name";
            QueryResultList = _productServices.FindProductsByProductName(QueryProductName);

            //return RedirectToPage();
        }

        public IActionResult OnPostClearForm()
        {
            FeedbackMessage = "You click on Clear button";
            //SelectedCategoryId = 0;
            //QueryProductName = null;
            return RedirectToPage();
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/Territories/Query.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using WestwindSystem.Entities;
using WestwindSystem.BLL;
using WestwindWebApp.Helpers;

namespace WestwindWebApp.Pages.Territories
{
    public class QueryModel : PageModel
    {
        private readonly RegionServices _regionServices;
        private readonly TerritoryServices _territoryServices;

        public QueryModel(RegionServices regionServices, TerritoryServices territoryServices)
        {
            _regionServices = regionServices;
            _territoryServices = territoryServices;

            Regions = _regionServices.GetAll();
        }

        public List<Region> Regions { get; private set; }

        [BindProperty]
        public int? SelectedRegionId { get; set; }

        public List<Territory> QueryResultList { get; private set; }

        public string? FeedbackMessage { get; set; }

        [BindProperty]
        public string TerritoryQuery { get; set; }

        #region Paginator
        //my desired page size
        private const int PAGE_SIZE = 5;
        //be able to hold an instance of the Paginator
        public Paginator Pager { get; set; }
        #endregion

        [BindProperty(SupportsGet = true)]
        public string InfoMessage { get; set; }
        public string ErrorMessage { get; set; }

        [BindProperty(SupportsGet = true)]
        public string? SearchBy { get; set; }
        [BindProperty(SupportsGet = true)]
        public string? SearchValue { get; set; }

        public void OnGet(int? currentPage)
        {
            if (SearchBy != null && SearchValue != null)
            {
                if (SearchBy.ToLower() == "territory")
                {
                    //determine the current page number
                    int pagenumber = currentPage.HasValue ? currentPage.Value : 1;
                    //setup the current state of the paginator (sizing)
                    PageState current = new(pagenumber, PAGE_SIZE);
                    //temporary local integer to hold the results of the query's total collection size
                    //  this will be need by the Paginator during the paginator's execution
                    int totalcount;

                    try
                    {
                        QueryResultList = _territoryServices.FindByPartialName(SearchValue, pagenumber, PAGE_SIZE, out totalcount);
                        //create the needed Pagnator instance
                        Pager = new Paginator(totalcount, current);

                        InfoMessage = $"Query returned {QueryResultList.Count} results";
                    }
                    catch (Exception ex)
                    {
                        ErrorMessage = $"Error searching by territory with exception: {ex.Message} ";
                    }

                }
                else if (SearchBy.ToLower() == "region")
                {
                    //determine the current page number
                    int pagenumber = currentPage.HasValue ? currentPage.Value : 1;
                    //setup the current state of the paginator (sizing)
                    PageState current = new(pagenumber, PAGE_SIZE);
                    //temporary local integer to hold the results of the query's total collection size
                    //  this will be need by the Paginator during the paginator's execution
                    int totalcount;

                    try
                    {
                        int selectedRegionId = int.Parse(SearchValue);
                        QueryResultList = _territoryServices.FindByRegionId(selectedRegionId, pagenumber, PAGE_SIZE, out totalcount);
                        //create the needed Pagnator instance
                        Pager = new Paginator(totalcount, current);

                        InfoMessage = $"Query returned {QueryResultList.Count} results";
                    }
                    catch (Exception ex)
                    {
                        ErrorMessage = $"Error searching by region with exception: {ex.Message} ";
                    }
                }
                else
                {
                    ErrorMessage = $"{SearchBy} is not a supported search by value";
                }
            }
        }

        public IActionResult OnPostFilterByTerritory()
        {
            IActionResult nextPage = Page();
            if (TerritoryQuery != null)
            {
                //QueryResultList = _territoryServices.FindByPartialName(TerritoryQuery);
                SearchBy = "territory";
                SearchValue = TerritoryQuery;
                nextPage = RedirectToPage(new { SearchBy = SearchBy, SearchValue = TerritoryQuery });
            }
            else
            {
                FeedbackMessage = "You need to enter a territory first.";
            }

            return nextPage;
        }

        public IActionResult OnPostFilterByRegion()
        {
            IActionResult nextPage = Page();
            // Check if a valid region was selected
            if (SelectedRegionId.HasValue)
            {
                //QueryResultList = _territoryServices.FindByRegionId(SelectedRegionId.Value);
                SearchBy = "region";
                SearchValue = SelectedRegionId.Value.ToString();
                nextPage = RedirectToPage(new { SearchBy = SearchBy, SearchValue = SearchValue });
            }
            else
            {
                FeedbackMessage = "You must select a region first.";
            }

            return nextPage;
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/Territories/TerritoryCRUD.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WestwindSystem.BLL;
using WestwindSystem.Entities;

namespace WestwindWebApp.Pages.Territories
{
    public class TerritoryCRUDModel : PageModel
    {
        private readonly RegionServices _regionService;
        private readonly TerritoryServices _territoryServices;

        // The EditTerritoryId property value is read from the route of the page
        [BindProperty(SupportsGet = true)]
        public string? EditTerritoryId { get; set; }

        // The current Territory to create, edit/udpate, or delete
        [BindProperty]
        public Territory? CurrentTerritory { get; set; }

        public SelectList RegionSelectList { get; private set; }

        [BindProperty(SupportsGet = true)]
        public int? SelectedRegionId { get; set; }

        [TempData]
        public string? InfoMessage { get; set; }

        [TempData]
        public string? ErrorMessage { get; set; }

        public TerritoryCRUDModel(RegionServices regionServices, TerritoryServices territoryServices)
        {
            _regionService = regionServices;
            _territoryServices = territoryServices;

            RegionSelectList = new SelectList(_regionService.GetAll(), "RegionId", "RegionDescription");
        }

        private Exception GetInnerException(Exception ex)
        {
            //drill down to the REAL ERROR message
            while (ex.InnerException != null)
            {
                ex = ex.InnerException;
            }
            return ex;
        }

        public IActionResult OnPostSaveNew()
        {
            IActionResult nextPage = Page();

            if (SelectedRegionId.HasValue && SelectedRegionId.Value > 0)
            {
                int regionId = SelectedRegionId.Value;
                CurrentTerritory.RegionId = regionId;
                // Remove the Territory key from ModelState of the CurrentTerritory
                // to work around issue where the generated entities include navigation properties that are not set yet
                ModelState.Remove("CurrentTerritory.Region");
                //CurrentTerritory.Region = _regionService.GetById(SelectedRegionId.Value);

                if (ModelState.IsValid && CurrentTerritory != null)
                {
                    try
                    {
                        _territoryServices.AddTerritory(CurrentTerritory);
                        InfoMessage = "Save New was successful";
                        //EditTerritoryId = CurrentTerritory.TerritoryId;
                        nextPage = RedirectToPage(new { EditTerritoryId = CurrentTerritory.TerritoryId });
                    }
                    catch (Exception ex)
                    {
                        ErrorMessage = GetInnerException(ex).Message;
                    }
                }
                else
                {
                    ErrorMessage = $"<p>ModelState is not valid with the following errors:</p>";
                    ErrorMessage += "<ul>";
                    foreach (var modelState in ViewData.ModelState.Values)
                    {
                        foreach (var error in modelState.Errors)
                        {
                            ErrorMessage += $"<li>{error.ErrorMessage}</li>";
                        }
                    }
                    ErrorMessage += "</ul>";
                }
            }
            else
            {
                ErrorMessage = "A valid Region must be selected";
            }



            return nextPage;
        }

        public void OnGet()
        {
            if (EditTerritoryId != null)
            {
                CurrentTerritory = _territoryServices.GetById(EditTerritoryId);
                if (CurrentTerritory != null)
                {
                    SelectedRegionId = CurrentTerritory.RegionId;
                }
            }
            else
            {
                ErrorMessage = null;
            }
        }

        public IActionResult OnPostUpdate()
        {
            IActionResult nextPage = Page();

            if (SelectedRegionId.HasValue && SelectedRegionId.Value > 0)
            {
                int regionId = SelectedRegionId.Value;
                CurrentTerritory.RegionId = regionId;
                // Remove the Territory key from ModelState of the CurrentTerritory
                // to work around issue where the generated entities include navigation properties that are not set yet
                ModelState.Remove("CurrentTerritory.Region");
                CurrentTerritory.Region = _regionService.GetById(SelectedRegionId.Value);

                if (ModelState.IsValid && CurrentTerritory != null)
                {
                    try
                    {
                        int rowsAffected = _territoryServices.UpdateTerritory(EditTerritoryId, CurrentTerritory);
                        if (rowsAffected == 1)
                        {
                            InfoMessage = "Update was successful";
                        }
                        else
                        {
                            InfoMessage = "Update was not successful";
                        }

                    }
                    catch (Exception ex)
                    {
                        ErrorMessage = GetInnerException(ex).Message;
                    }
                }
                else
                {
                    ErrorMessage = $"ModelState is not valid.";
                    foreach (var modelState in ViewData.ModelState.Values)
                    {
                        foreach (var error in modelState.Errors)
                        {
                            ErrorMessage += error.ErrorMessage + "<br />";
                        }
                    }
                }
            }
            else
            {
                ErrorMessage = $"A valid region must be selected.";
            }



            return nextPage;
        }

        public IActionResult OnPostDelete()
        {
            IActionResult nextPage = Page();

            if (EditTerritoryId != null)
            {
                try
                {
                    int rowsAffected = _territoryServices.DeleteTerritory(EditTerritoryId);
                    if (rowsAffected == 1)
                    {
                        InfoMessage = "Delete was successful.";
                        //nextPage = RedirectToPage("/Territories/Query", new { InfoMessage = InfoMessage});
                        nextPage = RedirectToPage(new { EditTerritoryId = (int?)null });
                    }
                    else
                    {
                        InfoMessage = "Delete was not successful.";
                    }
                }
                catch (Exception ex)
                {
                    ErrorMessage = GetInnerException(ex).Message;
                }
            }
            else
            {
                ErrorMessage = "Error! You have not selected an Territory to delete.";
            }
            return nextPage;
        }

        public IActionResult OnPostClear()
        {
            IActionResult nextPage = Page();
            EditTerritoryId = null;
            CurrentTerritory = new();
            ModelState.Clear();

            return nextPage;
        }

        public IActionResult OnPostSearch()
        {
            IActionResult nextPage = Redirect("/Territories/Query");

            return nextPage;
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/Territories/Index.cshtml
@page
@model WestwindWebApp.Pages.Territories.IndexModel
@{
}
<h1>Territories</h1>
@if (Model.InfoMessage != null)
{
    <div class="alert alert-info">
        @Model.InfoMessage
    </div>
}

@if (Model.ErrorMessage != null)
{
    <div class="alert alert-danger">
        @Model.ErrorMessage
    </div>
}
@if (Model.TerritoryList.Count != null && Model.TerritoryList.Count > 0)
{
    <table class=" table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Description</th>
                <th>Region</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var currentTerritory in Model.TerritoryList)
            {
                <tr>
                    <td>@currentTerritory.TerritoryId</td>
                    <td>@currentTerritory.TerritoryDescription</td>
                    <td>@currentTerritory.Region.RegionDescription</td>
                </tr>
            }
        </tbody>
        <tfoot>

            @*used for summay table information eg totals
        used for displaying paging information
        *@
            <tr>
                <td colspan="3">
                    @{
                        //the pageRef is the string representation of the
                        //  the value to be displayed AND it's numeric
                        //the string maybe be a character line : Next
                        //the string maybe be a numeric : 4
                        //  First Previous 1 2 3 4 5 Next Last
                        foreach (var pageRef in Model.Pager)
                        {
                            if (pageRef == Model.Pager.CurrentPage)
                            {
                                <b>@pageRef.Text</b>
                            }
                            else
                            {
                                //create an anchor tag to move to
                                //  the desired collection page
                                //the target of the anchor destination
                                //  is your current web cshtml
                                //this will cause a OnGet issue
                                // .Page is the numeric representation
                                //      of the desired page
                                //for the asp-page your page name reference
                                //  MUST be based from the folder name Pages....and will always customize the asp-page
                                <a title="Page @pageRef.Page"
                   asp-page="/Territories/Index" 
                   asp-route-currentpage="@pageRef.Page">
                                    @pageRef.Text
                                </a>
                            }
                        }
                    }
                </td>
            </tr>
        </tfoot>

    </table>
}

WestwindSolution/WestwindWebApp/Pages/Territories/Query.cshtml
@page "{SearchBy?}/{SearchValue?}/{TerritoryQuery?}"
@model WestwindWebApp.Pages.Territories.QueryModel
@{
}
<h1>Territory Queries</h1>

@if (Model.FeedbackMessage != null)
{
    <div class="alert alert-warning">
        @Model.FeedbackMessage
    </div>
}

<form method="post">
    <div>
        <label asp-for="SelectedRegionId">Select region:</label>
        <select asp-for="SelectedRegionId"
                class="form-select">
            <option selected>Open this select menu</option>
            @foreach (var currentRegion in Model.Regions)
            {
                <option value="@currentRegion.RegionId">@currentRegion.RegionDescription</option>
            }
        </select>
    </div>
    <div>
        <label asp-for="TerritoryQuery">Name:</label>
        <input asp-for="TerritoryQuery" class="form-control" />
    </div>
    <div>
        <button type="submit"
                asp-page-handler="FilterByRegion"
                class="btn btn-primary">
            Search by Region
        </button>
        <button type="submit"
                asp-page-handler="FilterByTerritory"
                class="btn btn-primary">
            Search by Name
        </button>
    </div>
</form>

@if (Model.QueryResultList != null && Model.QueryResultList.Count > 0)
{
    <table>
        <thead>
            <tr>
                <th style="width: 200px">ID</th>
                <th>Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var currentTerritory in Model.QueryResultList)
            {
                <tr>
                    <td>@currentTerritory.TerritoryId</td>
                    <td>@currentTerritory.TerritoryDescription</td>
                    <td>
                        <a href="/Territories/TerritoryCRUD/@currentTerritory.TerritoryId">
                            Edit
                        </a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>

            @*used for summay table information eg totals
        used for displaying paging information
        *@
            <tr>
                <td colspan="3">
                    @{
                        //the pageRef is the string representation of the
                        //  the value to be displayed AND it's numeric
                        //the string maybe be a character line : Next
                        //the string maybe be a numeric : 4
                        //  First Previous 1 2 3 4 5 Next Last
                        foreach (var pageRef in Model.Pager)
                        {
                            if (pageRef == Model.Pager.CurrentPage)
                            {
                                <b>@pageRef.Text</b>
                            }
                            else
                            {
                                //create an anchor tag to move to
                                //  the desired collection page
                                //the target of the anchor destination
                                //  is your current web cshtml
                                //this will cause a OnGet issue
                                // .Page is the numeric representation
                                //      of the desired page
                                //for the asp-page your page name reference
                                //  MUST be based from the folder name Pages
                                <a title="Page @pageRef.Page"
                   asp-page="/Territories/Query"
                   asp-route-currentpage="@pageRef.Page"
                   asp-route-TerritoryQuery="@Model.TerritoryQuery">
                                    @pageRef.Text
                                </a>
                            }
                        }
                    }
                </td>
            </tr>
        </tfoot>
    </table>
}

WestwindSolution/WestwindWebApp/Pages/Territories/TerritoryCRUD.cshtml
@page "{EditTerritoryId?}"

@model WestwindWebApp.Pages.Territories.TerritoryCRUDModel
@{
}

<h1>Territory Maintenance  </h1>
@if (Model.EditTerritoryId != null)
{
    <h2>Edit Territory @Model.EditTerritoryId</h2>
}
else
{
    <h2>New Territory</h2>
}

@if (Model.InfoMessage != null)
{
    <div class="alert alert-info">
        @Model.InfoMessage
    </div>
}

@if (Model.ErrorMessage != null)
{
    <div class="alert alert-danger">
        @Html.Raw( @Model.ErrorMessage )
    </div>
}


<form method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div>
        <label asp-for="CurrentTerritory.TerritoryId">ID:</label>
        <input asp-for="CurrentTerritory.TerritoryId"
               class="form-control" />
        <span asp-validation-for="CurrentTerritory.TerritoryId"></span>
    </div>
    <div>
        <label asp-for="CurrentTerritory.TerritoryDescription">Description:</label>
        <input asp-for="CurrentTerritory.TerritoryDescription"
               class="form-control" />
        <span asp-validation-for="CurrentTerritory.TerritoryDescription"></span>
    </div>
    <div>
        <label asp-for="SelectedRegionId">Select region:</label>
        <select asp-for="SelectedRegionId"
                asp-items="Model.RegionSelectList"
                class="form-select">
            <option>--- select a region ---</option>
        </select>
        <span asp-validation-for="CurrentTerritory.RegionId"></span>
    </div>

    <div>
        @if (Model.EditTerritoryId == null)
        {
            <button type="submit"
                asp-page-handler="SaveNew"
                class="btn btn-primary">
                Save New
            </button>
        }

        @if (Model.EditTerritoryId != null)
        {
            <button type="submit"
                asp-page-handler="Update"
                class="btn btn-info">
                Update
            </button>
            <button type="submit"
                asp-page-handler="Delete"
                class="btn btn-danger"
                formnovalidate
                onclick="return confirm('Are you sure you wish to delete this item?')">
                Delete
            </button>
        }

        <button type="submit"
                asp-page-handler="Clear"
                class="btn btn-secondary"
                formnovalidate>
            Clear
        </button>
        <button type="submit"
                asp-page-handler="Search"
                class="btn btn-link"
                formnovalidate>
            Search
        </button>
    </div>

</form>