WestwindSolution/WestwindWebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WestwindWebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/FormControlDemoUsingPureHtml.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WestwindWebApp.Pages
{
    public class FormControlDemoUsingPureHTMLModel : PageModel
    {
        [TempData]
        public string FeedbackMessage { get; set; }

        [BindProperty]
        public string Username { get; set; }

        [BindProperty]
        public int Age { get; set; }

        public void OnGet()
        {

        }

        public void OnPost()
        {
            FeedbackMessage = $"Username = {Username}, Age = {Age}";
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/FormControlDemoUsingTagHelpers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WestwindWebApp.Pages
{
    public class FormControlDemoUsingTagHelpersModel : PageModel
    {
        [TempData]
        public string FeedbackMessage { get; set; }

        [BindProperty]
        public string Username { get; set; }

        [BindProperty]
        public int Age { get; set; }

        [BindProperty]
        public string Gender { get; set; }

        [BindProperty]
        public string Department { get; set; }

        [BindProperty]
        public bool Subscribe { get; set; }

        [BindProperty]
        public string Comments { get; set; }

        public void OnGet()
        {

        }

        public void OnPost()
        {
            
            if (Age >= 85)
            {
                FeedbackMessage = FeedbackMessage = $"Username = {Username}, Age = {Age}, Gender = {Gender}, Department = {Department}, Subscribed? = {Subscribe}, Your comments = {Comments}, My comments = Damn you old lmao";
            }
            else
            {
                FeedbackMessage = $"Username = {Username}, Age = {Age}, Gender = {Gender}, Department = {Department}, Subscribed? = {Subscribe}, Your comments = {Comments}";
            }
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region custom namespaces
using WestWindSystem.BLL;
using WestWindSystem.Entities;     //specifies which namespace is and folders its using 
#endregion

namespace WestwindWebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        private readonly BuildVersionServices _buildVersionServices;
        public IndexModel(ILogger<IndexModel> logger, BuildVersionServices buildVersionServices) // constructor dependency injection
        {
            _logger = logger;
            _buildVersionServices = buildVersionServices;
        }

        public BuildVersion CurrentBuildVersion { get; set; } = null!;
        public void OnGet() //everytime there is onGet request , its gonna fetchh buildversion
        {
            CurrentBuildVersion = _buildVersionServices.GetBuildVersion();
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WestwindWebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/ProjectSelection.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WestwindWebApp.Models;

namespace WestwindWebApp.Pages
{
    public class ProjectSelectionModel : PageModel
    {
        private readonly IHostEnvironment environment;

        public ProjectSelectionModel()
        {
            NumberOfGroups = 5;
            using (StreamReader reader = new StreamReader("wwwroot/data/CPSC1517.1221.A03.ClassList.txt"))//construct stream reader object
            {
                reader.ReadLine();//read online  at a time
                string line;
                while ((line = reader.ReadLine()) != null)
                {
                    string[] parts = line.Split(',');//file is separated by comma and starting from the right is the index fname[0],lname[1],id[2]
                    Student currentStudent = new Student(); //currentStudent to generate a new student in the list
                    currentStudent.Id = int.Parse(parts[2]);
                    currentStudent.FirstName = parts[0];
                    currentStudent.LastName = parts[1];
                    Students.Add(currentStudent);//to add the student in the list
                }
            }
            AvailableScenariosDict.Add("Group1", "Scenario A01");
            AvailableScenariosDict.Add("Group2", "Scenario A02");
            AvailableScenariosDict.Add("Group3", "Scenario A03");
            AvailableScenariosDict.Add("Group4", "Scenario A04");
            AvailableScenariosDict.Add("Group5", "Scenario A14");
        }
        public List<Student> Students { get; private set; } = new(); /*= new List<Student>();*/

        [BindProperty]
        public int NumberOfGroups { get; private set; }

        public Dictionary<string,string> AvailableScenariosDict { get; private set; } = new();

        public Dictionary<string, List<Student>> StudentGroupDict { get; private set; } = new();


        public void OnGet()
        {

        }


        public void OnPostSplitIntoGroups()
        {
            // Determine the number of members per group
            int membersPerGroup = (int)Math.Ceiling(1.0 * Students.Count / NumberOfGroups);
            // Clear all existing groups
            StudentGroupDict.Clear();
            // Create a copy of the Students list
            var studentListCopy = Students.ToList();
            // Create an object for generating random
            Random rand = new();
            // Create a number to track the current group
            int currentGroup = 1;
            // Repeat until all students have been removed from studentListCopy
            while (studentListCopy.Count > 0)
            {
                // Create a new list of student for each group
                List<Student> currentStudentGroup = new();
                // Create a unique group name
                string groupName = $"Group{currentGroup}";


                for (int memberCount = 1; memberCount <= membersPerGroup && studentListCopy.Count > 0; memberCount++)
                {
                    // Generate a random index for the element to remove
                    int randomIndex = rand.Next(0, studentListCopy.Count);
                    // Add the current element to the student group
                    currentStudentGroup.Add(studentListCopy[randomIndex]);
                    // Remove the current element from the list
                    studentListCopy.RemoveAt(randomIndex);
                }
                // Add the currentStudentGroup to the dictionary
                StudentGroupDict.Add(groupName, currentStudentGroup);
                // Set the next currentGroup
                currentGroup++;
            }

        }
    }
}

WestwindSolution/WestwindWebApp/Pages/SendMail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Net;
using System.Net.Mail;

namespace WestwindWebApp.Pages
{
    public class SendMailModel : PageModel
    {
        public void OnGet() 
        {
            //introduction instruction on dependancy injection
            //var gmailUsername = Configuration["GmailCredentials:Username"];  
            //var gmailAppPassword = Configuration["GmailCredentials:Password"];
            //FeedBackMessage = $"Gmail username = {gmailUsername} <br />";
            //FeedBackMessage += $"Gmail app password = {gmailAppPassword} <br />";
        }

        private readonly IConfiguration Configuration;
        public SendMailModel(IConfiguration configuration) //constructor dependency injection getting the configuration for the setting (configuration)
        {
            this.Configuration = configuration;  //relates to json file appsetting
        }

        [BindProperty]
        public string FeedBackMessage { get; set; }

        [BindProperty]
        public string Username { get; set; }

        [BindProperty]
        public string Password { get; set; }

        [BindProperty]
        public string Recipient { get; set; }

        [BindProperty]
        public string MailSubject { get; set; }

        [BindProperty]
        public string MailMessage { get; set; }

        //page handler methods
        public void OnPostSendMail()
        {
            //FeedBackMessage = "<h2>Send Mail button clicked</h2>";

            var sendMailClient = new SmtpClient(); //smtp protocol that allows you to send email
            sendMailClient.Host = "smtp.gmail.com"; //to send email specify which server to send it
            sendMailClient.Port = 587; //need to set what port to yuse
            sendMailClient.EnableSsl = true; 
            var sendMailCredentials = new NetworkCredential(); // identity of the user by specifying their user name and password
            Username = Configuration["GmailCredentials:Username"];
            Password = Configuration["GmailCredentials:Password"];
            sendMailCredentials.UserName = Username;
            sendMailCredentials.Password = Password;
            sendMailClient.Credentials = sendMailCredentials;

            var sendFromAddress = new MailAddress(Username);
            var sendToAddress = new MailAddress(Recipient);

            var mailMessage = new MailMessage(sendFromAddress, sendToAddress);
            mailMessage.Subject = MailSubject;
            mailMessage.Body = MailMessage;

            try
            {
                sendMailClient.Send(mailMessage);
                //clear the form fields associated with the properties below
                MailSubject = "";
                MailMessage = "";
                Recipient = "";
                FeedBackMessage = "<div class='alert alert-primary'>Email Sent!</div>";
            }
            catch (Exception ex)
            {
                FeedBackMessage = $"<div class='alert alert-danger'>Error sending email {ex}!</div>";

            }
            
        }

        public void OnPostClearForm()
        {
            FeedBackMessage = "<h2>Clear Form button clicked</h2>";
        }

        public void OnPost()
        {

        }
    }
}

WestwindSolution/WestwindWebApp/Pages/FormControlDemoUsingPureHtml.cshtml
@page
@model WestwindWebApp.Pages.FormControlDemoUsingPureHTMLModel
@{
}
<div class="alert-info">
    @Model.FeedbackMessage

</div>
<form method="post">
    <div class="mb-3">
        <label for="Username" class="form-label">Username</label>
        <input type="text" class="form-control" id="Username" name="Username" value="@Model.Username"/>
    </div>
    <div class="mb-3">
        <label for="Age" class="form-label">Age</label>
        <input type="number" min="18" max="65" class="form-control" id="Age" name="Age" value="@Model.Age"/>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

WestwindSolution/WestwindWebApp/Pages/FormControlDemoUsingTagHelpers.cshtml
@page
@model WestwindWebApp.Pages.FormControlDemoUsingTagHelpersModel
@{
}
<div class="alert-info">
    @Model.FeedbackMessage
</div>
<form method="post">

    <div class="mb-3">
        <label asp-for="Username" class="form-label">Username</label>
        <input type="text" class="form-control" placeholder="Enter your name" asp-for="Username" />
    </div>

    <div class="mb-3">
        <label asp-for="Age" class="form-label">Age</label>
        <input type="number" min="18" max="100" class="form-control" asp-for="Age" />
    </div>

    <div class="mb-3">
        <label for="floatingSelect">Gender</label>
        <select class="form-select" id="floatingSelect" asp-for="Gender">
            <option selected>Select Your Gender</option>
            <option value="Male">Male</option>
            <option value="Female">Female</option>
            <option value="Other">Other</option>
        </select>
    </div>

    <div class="mb-3">
        <label for="floatingSelect">Department</label>
        <select class="form-select" asp-for="Department">
            <option selected>Select Your Department</option>
            <option value="BAIST">BAIST</option>
            <option value="DMIT">DMIT</option>
            <option value="CNT">CNT</option>
            <option value="CET">CET</option>
        </select>
    </div>

    <div class="mb-3">
        <input class="form-check-input" type="checkbox" asp-for="Subscribe"> 
        <label class="form-check-label" for="flexCheckDefault">
            Would You Like Subscribe?
        </label>
    </div>

    <div class="mb-3">
        <label for="floatingTextarea">Comments</label>
        <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea" asp-for="Comments"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

</form>

WestwindSolution/WestwindWebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

@if (Model.CurrentBuildVersion == null)
{
    <div class="alert alert-warning" role="alert">
        Build Version Unknown
    </div>
}
else
{
    <div class="alert alert-info" role="alert">
        Database Version: @Model.CurrentBuildVersion.Major . @Model.CurrentBuildVersion.Minor . @Model.CurrentBuildVersion.Build
        &nbsp;
        released on @Model.CurrentBuildVersion.ReleaseDate.ToString("MMM dd, yyyy")
    </div>
}

WestwindSolution/WestwindWebApp/Pages/ProjectSelection.cshtml
@page
@model WestwindWebApp.Pages.ProjectSelectionModel
@{
} 
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var currentStudent in Model.Students)
        {
            <tr>
                <td>@currentStudent.Id</td>
                <td>@currentStudent.FullName</td>
            </tr>
        }
    </tbody>
</table>

<h2>Available Scenarios</h2>
<ol>
    @foreach(var currentScenario in Model.AvailableScenariosDict.Values)
    {
        <li>@currentScenario</li>
    }
</ol>

<h2>Project Selection Assignment</h2>
@if (Model.StudentGroupDict.Count > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Group Name</th>
                <th>Scenario</th>
                <th>Group Members</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var kvp in Model.StudentGroupDict)
            {
                <tr>
                    <td>@kvp.Key</td>
                    <td>@Model.AvailableScenariosDict[kvp.Key]</td>
                    <td>
                        <ol>
                            @foreach(var currentstudent in kvp.Value)
                            {
                                <li>@currentstudent.FullName</li>
                            }
                        </ol>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

<form method="post">
    <div class="row">
        <div class="col">
            <label asp-for="NumberOfGroups">Number of Groups</label>
            <input asp-for="NumberOfGroups" class="form-control" />
        </div>
        <div class="col">
            <button type="submit" asp-page-handler="SplitIntoGroups">Split into Groups</button>
        </div>
    </div>
</form>

WestwindSolution/WestwindWebApp/Pages/SendMail.cshtml
@page
@model WestwindWebApp.Pages.SendMailModel
@{
}
<h1>Email Client App</h1>
<div class="alert alert-info">
    @Html.Raw(Model.FeedBackMessage)
</div>
<form method="post">
    @*<div class="row mb-3">
        <div class="col-sm-2 col-form-label">
            <label asp-for="Username" class="form-label">Gmail Username:</label>
        </div>
        <div class="col-auto">
            <input asp-for="Username" type="text" class="form-control" required >
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-sm-2 col-form-label">
            <label asp-for="Password" class="col-form-label">Gmail App Password:</label>
        </div>
        <div class="col-auto">
            <input asp-for ="Password" type="password" class="form-control">
        </div>
    </div>*@



    <div class="row mb-3">
        <div class="col-sm-2 col-form-label">
            <label asp-for="Recipient" class="form-label">Mail To:</label>
        </div>
        <div class="col-auto">
            <input type="email" class="form-control" asp-for="Recipient">
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-sm-2 col-form-label">
            <label asp-for="MailSubject" class="form-label">Subject:</label>
        </div>
        <div class="col-auto">
            <input asp-for="MailSubject" class="form-control"/>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-sm-2 col-form-label">
            <label asp-for="MailMessage">Message:</label>
        </div>
        <div class="col-sm-3">
            <textarea class="form-control" asp-for="MailMessage" rows="10" cols="50"></textarea>
        </div>
    </div>

    <button type="submit" 
        asp-page-handler="SendMail"
        class="btn btn-primary">Send Mail</button>
    <button type="submit" 
        asp-page-handler="ClearForm"
        class="btn btn-secondary">Clear</button>
</form>