WestwindSolution/WestwindWebApp/Pages/Products/ProductCRUD.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WestwindSystem.Entities;
using WestWindSystem.BLL;
using WestWindSystem.Entities;

namespace WestwindWebApp.Pages.Products
{
    public class ProductCRUDModel : PageModel
    {
        #region internal fields
        private readonly CategoryServices _categoryServices;
        private readonly ProductServices _productServices;
        private readonly SupplierServices _supplierServices;
        #endregion

        #region data properties for page
        [BindProperty(SupportsGet = true)] //if this page is accessed it will automatically find a route EditProductId and if it findes it it sets it in this property
        public int? EditProductId { get; set; }
        //Data source for category select element
        public SelectList CategorySelectList { get; private set; }

        public SelectList SupplierSelectList { get; private set; }

        [BindProperty] //bindable property for value selected from select element 
        public int? SelectedCategoryId { get; set; }

        [BindProperty]
        public int? SelectedSupplierId { get; set; }

        //The Current Product to add, update, or delete.
        [BindProperty]
        public Product CurrentProduct { get; set; }

        public string InfoMessage { get; set; }
        public string ErrorMessage { get; set; }


        #endregion

        #region constructor with dependecies
        public ProductCRUDModel (CategoryServices categoryServices, ProductServices productServices, SupplierServices supplierServices)
        {
            _categoryServices = categoryServices;
            _productServices = productServices;
            _supplierServices = supplierServices;

            
            List<Category> categories = _categoryServices.List();
            CategorySelectList = new SelectList(categories, "Id", "CategoryName", SelectedCategoryId);

            List<Supplier> suppliers = _supplierServices.List();
            SupplierSelectList = new SelectList(suppliers, "SupplierId", "SelectListText");




        }
        #endregion

        #region page handlers
        public void OnGet()
        {
            if (EditProductId != null)
            {
                int productId = EditProductId.Value;
                var querySingleResult = _productServices.GetById(productId);
                if (querySingleResult != null)
                {
                    CurrentProduct = querySingleResult;
                }
                else
                {
                    ErrorMessage = $"Invalid product id of {EditProductId}";
                }
               
            }
        }

        #endregion



    }
}

WestwindSolution/WestwindWebApp/Pages/Products/ProductCategory.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WestwindSystem.Entities;

#region namepsaces for BLL and Entities
using WestWindSystem.BLL;
using WestWindSystem.Entities;
#endregion

namespace WestwindWebApp.Pages.Products
{
    public class ProductCategoryModel : PageModel
    {
        #region Setup constructor DI for BLL
        private readonly CategoryServices _categoryServices;
        private readonly ProductServices _productServices;
        private readonly SupplierServices _supplierServices;

        public ProductCategoryModel(CategoryServices categoryServices, ProductServices productServices, SupplierServices supplierServcies)
        {
            _categoryServices = categoryServices;
            _productServices = productServices;
            _supplierServices = supplierServcies;

            // Fetch from the system (CategoryServices) a list of Category
            List<Category> categories = _categoryServices.List();
            CategorySelectList = new SelectList(categories, "Id", "CategoryName", SelectedCategoryId); //populate dropdown selection menu

            List<Supplier> suppliers = _supplierServices.List();    
            SupplierSelectList = new SelectList(suppliers,"SupplierId", "SelectListText"); //selectListText is a property that gets 2 attribute that we need to display on the dropdownlist
          
        }
        #endregion

        #region Properties to populate Category select element and track is selected value
        //public List<Category> CategoryList { get; private set; }

        //Data source for category select element
        public SelectList CategorySelectList { get; private set; }

        public SelectList SupplierSelectList { get; private set; }
        
        [BindProperty] //bindable property for value selected from select element 
        public int? SelectedCategoryId { get; set; }

        
        public int? SelectedSupplierId { get; set; }
        
        //query result list propery
        public List<Product>? QueryProductResultList { get; private set; }
        #endregion

        //[BindProperty]
        //public string? QueryProductName { get; set; }

        //feedback message property
        
        public string? InfoMessage { get; set; }
        public string? ErrorMessage { get; set; }

       

        public void OnGet()
        {

        }

        public IActionResult OnPostFetchProducts()
        {
            IActionResult nextPage = Page();
            // verify that a valid category was selected
            if (SelectedCategoryId.HasValue && SelectedCategoryId.Value > 0)
            {
                int categoryId = SelectedCategoryId.Value;
                QueryProductResultList = _productServices.FindProductsByCategoryId(categoryId);
                InfoMessage = $"Query Returned {QueryProductResultList.Count} record(s).";
            }
            else
            {
                ErrorMessage = "A valid category must be selected";
            }
          
            return nextPage;
        }


        public IActionResult OnPostClear()
        {
            IActionResult nextPage = Page();
            SelectedCategoryId = null;
            QueryProductResultList = null;
            ModelState.Clear();


            return nextPage;
        }

        public IActionResult OnPostNewProduct()
        {
            IActionResult nextPage = RedirectToPage("/Products/ProductCRUD"); // inside the redirect page is the route you want it to redirect to. Razor pages access a route not a file name , do not inlcude file extension

            return nextPage;
        }
   
    }
}

WestwindSolution/WestwindWebApp/Pages/Products/Query.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

#region namepsaces for BLL and Entities
using WestWindSystem.BLL;
using WestWindSystem.Entities;
#endregion


namespace WestwindWebApp.Pages.Products
{
    public class QueryModel : PageModel
    {
        #region Setup constructor DI for BLL
        private readonly CategoryServices _categoryServices;
        private readonly ProductServices _productServices;

        public QueryModel(CategoryServices categoryServices, ProductServices productServices)
        {
            _categoryServices = categoryServices;
            _productServices = productServices;

            // Fetch from the system (CategoryServices) a list of Category
            CategoryList = _categoryServices.List();
            CategorySelectionList = new SelectList(_categoryServices.List(), "Id", "CategoryName", SelectedCategoryId); //populate dropdown selection menu

        }
        #endregion

        #region Properties to populate Category select element and track is selected value
        public List<Category> CategoryList { get; private set; }
        [BindProperty]
        public int? SelectedCategoryId { get; set; }

        public SelectList CategorySelectionList { get; private set; }
        #endregion

        [BindProperty]
        public string? QueryProductName { get; set; }

        [TempData]
        public string? FeedbackMessage { get; set; }

        public List<Product> QueryResultList { get; private set; }

        public void OnGet()
        {

        }

        public void OnPostSearchByCategory()
        {
            FeedbackMessage = "You click on Search By Category";
            QueryResultList = _productServices.FindProductsByCategoryId(SelectedCategoryId.Value);
            //return RedirectToPage(new { currentSelectedCategoryId = SelectedCategoryId });
        }

        public void OnPostSearchByProductName()
        {
            FeedbackMessage = "You click on Search By Product Name";
            QueryResultList = _productServices.FindProductsByProductName(QueryProductName);

            //return RedirectToPage();
        }

        public IActionResult OnPostClearForm()
        {
            FeedbackMessage = "You click on Clear button";
            //SelectedCategoryId = 0;
            //QueryProductName = null;
            return RedirectToPage();
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/Territories/Query.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using WestwindSystem.Entities;
using WestwindSystem.BLL;
using WestwindWebApp.Helpers;

namespace WestwindWebApp.Pages.Territories
{
    public class QueryModel : PageModel
    {
        private readonly RegionServices _regionServices;
        private readonly TerritoryServices _territoryServices;

        public QueryModel(RegionServices regionServices, TerritoryServices territoryServices)
        {
            _regionServices = regionServices;
            _territoryServices = territoryServices;

            Regions = _regionServices.GetAll();
        }

        public List<Region> Regions { get; private set; }

        [BindProperty]
        public int? SelectedRegionId { get; set; }

        public List<Territory> QueryResultList { get; private set; }

        public string? FeedbackMessage { get; set; }

        [BindProperty]
        public string TerritoryQuery { get; set; }

        #region Paginator
        //my desired page size
        private const int PAGE_SIZE = 5;
        //be able to hold an instance of the Paginator
        public Paginator Pager { get; set; }
        #endregion

        [BindProperty(SupportsGet = true)]
        public string InfoMessage { get; set; }
        public string ErrorMessage { get; set; }

        [BindProperty(SupportsGet = true)]
        public string? SearchBy { get; set; }
        [BindProperty(SupportsGet = true)]
        public string? SearchValue { get; set; }

        public void OnGet(int? currentPage)
        {
            if (SearchBy != null && SearchValue != null)
            {
                if (SearchBy.ToLower() == "territory")
                {
                    //determine the current page number
                    int pagenumber = currentPage.HasValue ? currentPage.Value : 1;
                    //setup the current state of the paginator (sizing)
                    PageState current = new(pagenumber, PAGE_SIZE);
                    //temporary local integer to hold the results of the query's total collection size
                    //  this will be need by the Paginator during the paginator's execution
                    int totalcount;

                    try
                    {
                        QueryResultList = _territoryServices.FindByPartialName(SearchValue, pagenumber, PAGE_SIZE, out totalcount);
                        //create the needed Pagnator instance
                        Pager = new Paginator(totalcount, current);

                        InfoMessage = $"Query returned {QueryResultList.Count} results";
                    }
                    catch (Exception ex)
                    {
                        ErrorMessage = $"Error searching by territory with exception: {ex.Message} ";
                    }

                }
                else if (SearchBy.ToLower() == "region")
                {
                    //determine the current page number
                    int pagenumber = currentPage.HasValue ? currentPage.Value : 1;
                    //setup the current state of the paginator (sizing)
                    PageState current = new(pagenumber, PAGE_SIZE);
                    //temporary local integer to hold the results of the query's total collection size
                    //  this will be need by the Paginator during the paginator's execution
                    int totalcount;

                    try
                    {
                        int selectedRegionId = int.Parse(SearchValue);
                        QueryResultList = _territoryServices.FindByRegionId(selectedRegionId, pagenumber, PAGE_SIZE, out totalcount);
                        //create the needed Pagnator instance
                        Pager = new Paginator(totalcount, current);

                        InfoMessage = $"Query returned {QueryResultList.Count} results";
                    }
                    catch (Exception ex)
                    {
                        ErrorMessage = $"Error searching by region with exception: {ex.Message} ";
                    }
                }
                else
                {
                    ErrorMessage = $"{SearchBy} is not a supported search by value";
                }
            }
        }

        public IActionResult OnPostFilterByTerritory()
        {
            IActionResult nextPage = Page();
            if (TerritoryQuery != null)
            {
                //QueryResultList = _territoryServices.FindByPartialName(TerritoryQuery);
                SearchBy = "territory";
                SearchValue = TerritoryQuery;
                nextPage = RedirectToPage(new { SearchBy = SearchBy, SearchValue = TerritoryQuery });
            }
            else
            {
                FeedbackMessage = "You need to enter a territory first.";
            }

            return nextPage;
        }

        public IActionResult OnPostFilterByRegion()
        {
            IActionResult nextPage = Page();
            // Check if a valid region was selected
            if (SelectedRegionId.HasValue)
            {
                //QueryResultList = _territoryServices.FindByRegionId(SelectedRegionId.Value);
                SearchBy = "region";
                SearchValue = SelectedRegionId.Value.ToString();
                nextPage = RedirectToPage(new { SearchBy = SearchBy, SearchValue = SearchValue });
            }
            else
            {
                FeedbackMessage = "You must select a region first.";
            }

            return nextPage;
        }
    }
}

WestwindSolution/WestwindWebApp/Pages/Products/ProductCRUD.cshtml
@page "{EditProductId?}"
@model WestwindWebApp.Pages.Products.ProductCRUDModel
@{
}
<h1> Product Maintenance</h1>

@if(Model.EditProductId.HasValue)
{
    <h2>Edit/Delete Product</h2>
}
else
{
        <h2>Create New Product</h2>
}

@if (Model.InfoMessage != null)
{
        <div class="alert alert-info">
        @Model.InfoMessage
        </div>
}

@if (Model.ErrorMessage != null)
{
        <div class="alert alert-da nger">
        @Model.ErrorMessage
        </div>
}

<form method="post">
    <div>
        <label asp-for="CurrentProduct.ProductName">Product Name</label>
        <input asp-for="CurrentProduct.ProductName" class="form-control"/>
    </div>
    <div>
        <label asp-for="CurrentProduct.UnitPrice">Unit Price</label>
        <input asp-for="CurrentProduct.UnitPrice" class="form-control" />
    </div>



</form>

WestwindSolution/WestwindWebApp/Pages/Products/ProductCategory.cshtml
@page
@model WestwindWebApp.Pages.Products.ProductCategoryModel

@if (Model.InfoMessage != null)
{
    <div class="alert alert-info">
        @Model.InfoMessage
    </div>
}

@if (Model.ErrorMessage != null)
{
    <div class="alert alert-danger">
        @Model.ErrorMessage
    </div>
}

<form method="post">
    <div class="mb-3">

        <label asp-for="SelectedCategoryId">Category</label>
@*         <select asp-for="SelectedCategoryId"
        class="form-select"
        aria-label="Category">
        <option selected >--- select a category ---</option>
        @foreach(var currentCategory in Model.CategoryList)
        {
        <option value="@currentCategory.Id">@currentCategory.CategoryName</option>
        }
        </select>*@
         <select asp-for="SelectedCategoryId"
                asp-items="Model.CategorySelectList"
                class="form-select form-select-lg mb-3"
                aria-label=".form-select-lg category">
            <option>--- select a category ---</option>
        </select>
    </div>

        @*<div class="mb-3">
        <label asp-for="QueryProductName" class="form-label">Product Name</label>
        <input class="form-control"
               asp-for="QueryProductName" />
         </div>*@

    <button type="submit" asp-page-handler="FetchProducts" class="btn btn-primary">Fetch Products</button>
    <button type="submit" asp-page-handler="Clear" class="btn btn-primary">Clear</button>
    <button type="submit" asp-page-handler="NewProduct" class="btn btn-primary">New Product</button>

</form>

@if (Model.QueryProductResultList != null && Model.QueryProductResultList.Count > 0)
{
    <table class="table" style="color:black; font-family: Verdana; ">
        <thead>
            <tr>
                <th>ID</th>
                <th>Product Name</th>
                <th>Supplier Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var currentProduct in Model.QueryProductResultList)
            {
                <tr>
                    <td>@currentProduct.Id</td>
                    <td>@currentProduct.ProductName</td>
                    <td>
                        <select>
                           
                            @foreach(var item in Model.SupplierSelectList) //use this for deliverable!! , this make sure the dropdown select in the supplier name is the actual supplier in regards of the Productname
                            {
                                if(int.Parse(item.Value) == currentProduct.SupplierId)
                                {
                                    <option value="@item.Value" selected="selected">@item.Text</option>
                                }
                                else
                                {
                                    <option value="@item.Value">@item.Text</option>
                                }    
                                
                            }
                        
                        </select>
                    </td>
                    <td><a href="/Products/ProductCRUD/@currentProduct.Id">Edit</a></td>
                </tr>
            }
        </tbody>
    </table>
}

WestwindSolution/WestwindWebApp/Pages/Products/Query.cshtml
@page
@model WestwindWebApp.Pages.Products.QueryModel

@if (!string.IsNullOrWhiteSpace(Model.FeedbackMessage))
{
    <div class="alert alert-info">
        @Model.FeedbackMessage
    </div>
}

<form method="post">
    <div class="mb-3">

        <label asp-for="SelectedCategoryId">Category</label>
        @* <select asp-for="SelectedCategoryId"
        class="form-select"
        aria-label="Category">
        <option selected >--- select a category ---</option>
        @foreach(var currentCategory in Model.CategoryList)
        {
        <option value="@currentCategory.Id">@currentCategory.CategoryName</option>
        }
        </select>*@
        <select asp-for="SelectedCategoryId"
                asp-items="Model.CategorySelectionList">
            <option selected>--- select a category ---</option>
        </select>
    </div>

    <div class="mb-3">
        <label asp-for="QueryProductName" class="form-label">Product Name</label>
        <input class="form-control"
               asp-for="QueryProductName" />
    </div>

    <button type="submit" asp-page-handler="SearchByCategory" class="btn btn-primary">Search by Category</button>
    <button type="submit" asp-page-handler="SearchByProductName" class="btn btn-primary">Search by Product Name</button>
    <button type="submit" asp-page-handler="ClearForm" class="btn btn-light">Clear</button>

</form>

@if (Model.QueryResultList != null)
{
    <table class="table" style="color:black; font-family: Verdana; ">
        <thead>
            <tr>
                <th>ID</th>
                <th>Product Name</th>
                <th>Unit Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var currentProduct in Model.QueryResultList)
            {
                <tr>
                    <td>@currentProduct.Id</td>
                    <td>@currentProduct.ProductName</td>
                    <td>@currentProduct.UnitPrice</td>
                </tr>
            }
        </tbody>
    </table>
}